# Generated by Django 5.1.1 on 2024-10-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('temperature', models.FloatField()),
                ('pulse', models.IntegerField()),
                ('blood_pressure', models.CharField(max_length=7)),
                ('headache', models.BooleanField()),
                ('stomach_pain', models.BooleanField()),
                ('throat_pain', models.BooleanField()),
                ('has_disease', models.BooleanField()),
            ],
        ),
    ]
